# Generated by Django 3.2 on 2021-05-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cake_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('Select Category', 'Select Category'), ('sample1', 'sample1'), ('sample2', 'sample2')], default='Select Category', max_length=30)),
                ('description', models.CharField(max_length=60)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=64)),
                ('phone', models.CharField(max_length=30)),
                ('house_name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('pin', models.IntegerField()),
            ],
        ),
    ]
