# Generated by Django 3.2 on 2021-05-14 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cake_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('Select Category', 'Select Category'), ('sample1', 'sample1'), ('sample2', 'sample2')], default='Select Category', max_length=30)),
                ('description', models.CharField(max_length=60)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=64)),
                ('message', models.CharField(max_length=250)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=64)),
                ('phone', models.CharField(max_length=30)),
                ('house_name', models.CharField(max_length=80)),
                ('location', models.CharField(max_length=60)),
                ('pin', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=30)),
                ('cake_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.cake_list')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
