# Generated by Django 3.2 on 2021-05-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake_list',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
