# Generated by Django 3.2 on 2021-05-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake_list',
            name='category',
            field=models.CharField(choices=[('Select Category', 'Select Category'), ('Popular flavours', 'Popular flavours'), ('Design Cakes', 'Design Cakes'), ('Jar Cakes', 'Jar Cakes'), ('Brownies', 'Brownies')], default='Select Category', max_length=30),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(default='Pending', max_length=30),
        ),
    ]
