# Generated by Django 3.2 on 2021-05-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210514_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake_list',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
