# Generated by Django 3.2 on 2021-05-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_orders_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='house_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='orders',
            name='location',
            field=models.CharField(max_length=60),
        ),
    ]
